-- RBook community operations, administration and privacy-conscious access telemetry.

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

alter table public.profiles add column if not exists last_seen_at timestamptz;

create table if not exists public.user_access (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  access_level text not null default 'member' check (access_level in ('member', 'moderator', 'administrator')),
  state text not null default 'enabled' check (state in ('enabled', 'disabled')),
  updated_at timestamptz not null default now()
);

insert into public.user_access (user_id, access_level)
select id, case when row_number() over (order by created_at asc) = 1 then 'administrator' else 'member' end
from public.profiles
on conflict (user_id) do nothing;

create or replace function public.create_user_access_record()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.user_access (user_id, access_level)
  values (
    new.id,
    case when exists (select 1 from public.user_access where access_level = 'administrator') then 'member' else 'administrator' end
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists profiles_create_user_access on public.profiles;
create trigger profiles_create_user_access after insert on public.profiles
for each row execute function public.create_user_access_record();
revoke execute on function public.create_user_access_record() from public, anon, authenticated;

create or replace function private.is_enabled_user()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.user_access
    where user_id = (select auth.uid()) and state = 'enabled'
  );
$$;

create or replace function private.can_moderate()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.user_access
    where user_id = (select auth.uid())
      and access_level in ('moderator', 'administrator')
      and state = 'enabled'
  );
$$;

create or replace function private.can_administer()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.user_access
    where user_id = (select auth.uid())
      and access_level = 'administrator'
      and state = 'enabled'
  );
$$;

grant execute on function private.is_enabled_user() to authenticated;
grant execute on function private.can_moderate() to authenticated;
grant execute on function private.can_administer() to authenticated;

alter table public.user_access enable row level security;
drop policy if exists "user_access_self_read" on public.user_access;
create policy "user_access_self_read" on public.user_access for select to authenticated
using (user_id = (select auth.uid()) or private.can_administer());
grant select on public.user_access to authenticated;

alter table public.notes add column if not exists is_hidden boolean not null default false;
alter table public.notes add column if not exists moderation_reason text;
alter table public.comments add column if not exists is_hidden boolean not null default false;
alter table public.comments add column if not exists deleted_at timestamptz;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('like', 'comment', 'follow', 'system')),
  note_id uuid references public.notes(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  message text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.content_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  note_id uuid references public.notes(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  reason text not null check (char_length(reason) between 2 and 500),
  review_state text not null default 'pending' check (review_state in ('pending', 'resolved', 'dismissed')),
  handled_by uuid references public.profiles(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  check ((note_id is not null)::int + (comment_id is not null)::int = 1)
);

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  session_id text,
  path text not null,
  method text not null default 'PAGEVIEW',
  status_code integer not null default 200,
  duration_ms integer,
  ip_masked text,
  country text,
  city text,
  user_agent text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  administrator_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_access_level_idx on public.user_access (access_level);
create index if not exists notifications_recipient_created_idx on public.notifications (recipient_id, created_at desc);
create index if not exists notifications_unread_idx on public.notifications (recipient_id, created_at desc) where read_at is null;
create index if not exists content_reports_state_idx on public.content_reports (review_state, created_at desc);
create index if not exists access_logs_created_idx on public.access_logs (created_at desc);
create index if not exists access_logs_path_created_idx on public.access_logs (path, created_at desc);
create index if not exists access_logs_user_created_idx on public.access_logs (user_id, created_at desc) where user_id is not null;
create index if not exists admin_audit_created_idx on public.admin_audit_logs (created_at desc);

create or replace function private.notify_like()
returns trigger language plpgsql security definer set search_path = '' as $$
declare owner_id uuid;
begin
  select author_id into owner_id from public.notes where id = new.note_id;
  if owner_id is not null and owner_id <> new.user_id then
    insert into public.notifications (recipient_id, actor_id, kind, note_id)
    values (owner_id, new.user_id, 'like', new.note_id);
  end if;
  return new;
end;
$$;

drop trigger if exists likes_create_notification on public.likes;
create trigger likes_create_notification after insert on public.likes
for each row execute function private.notify_like();

create or replace function private.notify_comment()
returns trigger language plpgsql security definer set search_path = '' as $$
declare owner_id uuid;
begin
  select author_id into owner_id from public.notes where id = new.note_id;
  if owner_id is not null and owner_id <> new.author_id then
    insert into public.notifications (recipient_id, actor_id, kind, note_id, comment_id)
    values (owner_id, new.author_id, 'comment', new.note_id, new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists comments_create_notification on public.comments;
create trigger comments_create_notification after insert on public.comments
for each row execute function private.notify_comment();

create or replace function private.notify_follow()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.notifications (recipient_id, actor_id, kind)
  values (new.following_id, new.follower_id, 'follow');
  return new;
end;
$$;

drop trigger if exists follows_create_notification on public.follows;
create trigger follows_create_notification after insert on public.follows
for each row execute function private.notify_follow();

alter table public.notifications enable row level security;
alter table public.content_reports enable row level security;
alter table public.access_logs enable row level security;
alter table public.admin_audit_logs enable row level security;

drop policy if exists "notifications_owner_read" on public.notifications;
drop policy if exists "notifications_owner_update" on public.notifications;
drop policy if exists "notifications_owner_delete" on public.notifications;
create policy "notifications_owner_read" on public.notifications for select to authenticated using (recipient_id = (select auth.uid()));
create policy "notifications_owner_update" on public.notifications for update to authenticated using (recipient_id = (select auth.uid())) with check (recipient_id = (select auth.uid()));
create policy "notifications_owner_delete" on public.notifications for delete to authenticated using (recipient_id = (select auth.uid()));

drop policy if exists "reports_submit" on public.content_reports;
drop policy if exists "reports_read" on public.content_reports;
drop policy if exists "reports_review" on public.content_reports;
create policy "reports_submit" on public.content_reports for insert to authenticated with check (reporter_id = (select auth.uid()) and private.is_enabled_user());
create policy "reports_read" on public.content_reports for select to authenticated using (reporter_id = (select auth.uid()) or private.can_moderate());
create policy "reports_review" on public.content_reports for update to authenticated using (private.can_moderate()) with check (private.can_moderate());

drop policy if exists "access_logs_admin_read" on public.access_logs;
drop policy if exists "admin_audit_admin_read" on public.admin_audit_logs;
create policy "access_logs_admin_read" on public.access_logs for select to authenticated using (private.can_administer());
create policy "admin_audit_admin_read" on public.admin_audit_logs for select to authenticated using (private.can_administer());

drop policy if exists "published_notes_public_read" on public.notes;
create policy "published_notes_public_read" on public.notes for select to anon, authenticated
using ((status = 'published' and is_hidden = false) or author_id = (select auth.uid()) or private.can_moderate());

drop policy if exists "notes_owner_insert" on public.notes;
create policy "notes_owner_insert" on public.notes for insert to authenticated
with check (author_id = (select auth.uid()) and private.is_enabled_user());

drop policy if exists "notes_owner_update" on public.notes;
create policy "notes_owner_update" on public.notes for update to authenticated
using ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate())
with check ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate());

drop policy if exists "notes_owner_delete" on public.notes;
create policy "notes_owner_delete" on public.notes for delete to authenticated
using ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate());

drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read" on public.comments for select to anon, authenticated
using ((is_hidden = false and deleted_at is null) or author_id = (select auth.uid()) or private.can_moderate());

drop policy if exists "comments_owner_insert" on public.comments;
create policy "comments_owner_insert" on public.comments for insert to authenticated
with check (
  author_id = (select auth.uid())
  and private.is_enabled_user()
  and exists (
    select 1 from public.notes
    where notes.id = comments.note_id and notes.status = 'published' and notes.is_hidden = false
  )
);

drop policy if exists "comments_owner_update" on public.comments;
create policy "comments_owner_update" on public.comments for update to authenticated
using ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate())
with check ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate());

drop policy if exists "comments_owner_delete" on public.comments;
create policy "comments_owner_delete" on public.comments for delete to authenticated
using ((author_id = (select auth.uid()) and private.is_enabled_user()) or private.can_moderate());

drop policy if exists "likes_owner_insert" on public.likes;
create policy "likes_owner_insert" on public.likes for insert to authenticated
with check (user_id = (select auth.uid()) and private.is_enabled_user());

drop policy if exists "favorites_owner_insert" on public.favorites;
create policy "favorites_owner_insert" on public.favorites for insert to authenticated
with check (user_id = (select auth.uid()) and private.is_enabled_user());

drop policy if exists "follows_owner_insert" on public.follows;
create policy "follows_owner_insert" on public.follows for insert to authenticated
with check (follower_id = (select auth.uid()) and private.is_enabled_user());

grant select, update, delete on public.notifications to authenticated;
grant select, insert, update on public.content_reports to authenticated;
grant select on public.access_logs, public.admin_audit_logs to authenticated;
